services:
  - type: web
    name: music-bot
    env: docker
    plan: free
    autoDeploy: true
    region: singapore  # or oregon/frankfurt depending on your location
    dockerfilePath: ./Dockerfile
